/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 24-Nov-2024 17:33:20
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 305
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* General type conversion for MATLAB generated C-code  */
/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2022b.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   uint16 filter coefficients.
 */
const int BPL = 305;
const uint16_t BP[305] = {
        0,      0,      3,      0,      1,      1,      0,      6,      0,
        2,      3,      0,     10,      0,      4,      4,      0,     15,
        0,      5,      6,      0,     21,      0,      7,      7,      0,
       25,      0,      8,      8,      0,     27,      0,      8,      8,
        0,     25,      0,      7,      6,      0,     17,      0,      3,
        2,      0,      0,      3,      0,      0,     16,      0,     25,
        0,      0,     42,      0,     54,      0,      0,     75,      0,
       89,      0,      0,    112,      0,    127,      0,      0,    149,
        0,    164,      0,      0,    183,      0,    194,      0,      0,
      207,      0,    213,      0,      0,    216,      0,    214,      0,
        0,    203,      0,    191,      0,      0,    164,      0,    140,
        0,      0,     96,      0,     60,      0,      0,      0,     32,
        0,     29,     39,      0,    194,      0,     82,     94,      0,
      382,      0,    143,    155,      0,    586,      0,    207,    220,
        0,    794,      0,    270,    283,      0,    991,      0,    329,
      339,      0,   1163,      0,    377,    386,      0,   1296,      0,
      413,    418,      0,   1380,      0,    432,    434,      0,   1409,
        0,    434,    432,      0,   1380,      0,    418,    413,      0,
     1296,      0,    386,    377,      0,   1163,      0,    339,    329,
        0,    991,      0,    283,    270,      0,    794,      0,    220,
      207,      0,    586,      0,    155,    143,      0,    382,      0,
       94,     82,      0,    194,      0,     39,     29,      0,     32,
        0,      0,      0,     60,      0,     96,      0,      0,    140,
        0,    164,      0,      0,    191,      0,    203,      0,      0,
      214,      0,    216,      0,      0,    213,      0,    207,      0,
        0,    194,      0,    183,      0,      0,    164,      0,    149,
        0,      0,    127,      0,    112,      0,      0,     89,      0,
       75,      0,      0,     54,      0,     42,      0,      0,     25,
        0,     16,      0,      0,      3,      0,      0,      2,      3,
        0,     17,      0,      6,      7,      0,     25,      0,      8,
        8,      0,     27,      0,      8,      8,      0,     25,      0,
        7,      7,      0,     21,      0,      6,      5,      0,     15,
        0,      4,      4,      0,     10,      0,      3,      2,      0,
        6,      0,      1,      1,      0,      3,      0,      0
};
