/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
 * Generated on: 24-Nov-2024 17:29:52
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 305
 * Stable            : Yes
 * Linear Phase      : Yes (Type 1)
 */

/* 
 * Expected path to tmwtypes.h 
 * /Applications/MATLAB_R2022b.app/extern/include/tmwtypes.h 
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.  
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   int8 filter coefficients.
 */
const int BPL = 305;
const int8_t BP[305] = {
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,   -1,    0,    0,    0,    1,
     -1,    1,    0,    0,    1,   -1,    1,    0,    0,    1,   -1,    1,
      0,    0,    1,   -1,    1,    0,    0,    1,   -1,    1,    0,    0,
      1,   -1,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,   -1,    1,   -1,    0,    0,   -1,    1,   -1,    1,
      1,   -2,    2,   -2,    1,    1,   -2,    3,   -3,    1,    1,   -3,
      4,   -3,    1,    1,   -4,    5,   -4,    1,    2,   -4,    5,   -4,
      2,    2,   -4,    5,   -4,    2,    2,   -4,    6,   -4,    2,    2,
     -4,    5,   -4,    2,    2,   -4,    5,   -4,    2,    1,   -4,    5,
     -4,    1,    1,   -3,    4,   -3,    1,    1,   -3,    3,   -2,    1,
      1,   -2,    2,   -2,    1,    1,   -1,    1,   -1,    0,    0,   -1,
      1,   -1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    1,   -1,    1,    0,    0,    1,   -1,    1,    0,    0,
      1,   -1,    1,    0,    0,    1,   -1,    1,    0,    0,    1,   -1,
      1,    0,    0,    1,   -1,    1,    0,    0,    0,   -1,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
      0,    0,    0,    0,    0
};
